### PR TITLE
macOS: Debug build with the 2.4-rel branch 

### PR DESCRIPTION
**Pull request by daschuer**
This finally allows to use release only configurations with Debug build type in Mixxx. 

This is now on top of 2.4 to have both branch consistent and no criss-cross merge later.
It has been tested here: 
https://github.com/daschuer/mixxx/actions/runs/7165627000

Windows builds still fail with the same configuration: 

```
LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
shout_mixxx.lib(tls.c.obj) : error LNK2019: unresolved external symbol SSL_get1_peer_certificate referenced in function tls_check_cert
mixxx.exe : fatal error LNK1120: 1 unresolved externals
```

I am not able to debug this remotely and I have given up.

### CODE REVIEW

**Comment by fwcd** [comment]
Did some quick smoke testing with the build you've linked, it seems to work fine.

**Comment by daschuer** [comment]
Let's wait until upstream is merged: https://github.com/microsoft/vcpkg/pull/35533 an than cherry-pick without an overlay.

**Comment by daschuer** [comment]
Upstream is merged, we can continue here.

**Review by JoergAtGithub — APPROVED** [review]
This works on Windows as the old buildenv.

**Comment by JoergAtGithub** [comment]
@fwcd Is the latest build of this buildenv still working on macOS? Can we merge this?

**Comment by fwcd** [comment]
Do you by chance have a link to a (Mixxx) build using this env?

**Comment by daschuer** [comment]
Here is my last experimental branch.
https://github.com/daschuer/mixxx/actions/runs/7191497521/job/19586306093
I have no build with the latest upstream cherry-pick. 

Do we need one? For my understanding the change is only relevant for your private build at home.

**Comment by fwcd** [comment]
Just tested the x64 buildenv from [the latest run](https://github.com/mixxxdj/vcpkg/actions/runs/7269047286) with https://github.com/mixxxdj/mixxx/pull/12370 (built locally under Rosetta), seems to work fine.

**Comment by JoergAtGithub** [comment]
Than let's merge this! Thank you!
